# Generated by Django 4.0.4 on 2022-05-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0004_alimento_mascota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alimento',
            old_name='nombre',
            new_name='nombre_alimento',
        ),
        migrations.RenameField(
            model_name='alimento',
            old_name='raza',
            new_name='nombre_mascota',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='tipo',
        ),
        migrations.AddField(
            model_name='alimento',
            name='peso',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mascota',
            name='duenio',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
